---
title: "Assigment - kNN DIY"
author:
  - name author here - Author Kayla Zhang
  - name reviewer here - Reviewer
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
   html_notebook:
    toc: true
    toc_depth: 2
---


```{r}
library(tidyverse)
library(googlesheets4)
library(class)
library(caret)
```

---

Choose a suitable dataset from [this](https://github.com/HAN-M3DM-Data-Mining/assignments/tree/master/datasets) folder and train  your own kNN model. Follow all the steps from the CRISP-DM model.


## Business Understanding
Using CO2, temperature, humidity and light to see wether the office has been used or not is a innovative way. The table shows the connection between these factors. 
Due to there are too much data in the table, machine learing will be helpful.

## Data Understanding
url <- "https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/assignments/master/datasets/KNN-occupancy.csv"
rawDF <- read_csv(url)
str(rawDF)


## Data Preparation
The first variable "date" is not contained with other infomation. Therefore, we can clean that data.
cleanDF <- rawDF[-1]
head(cleanDF)

Use that formula to see how many office has been occupancy.
(1:occupancy, 0:not occupied)
cntDiag <- table(cleanDF$Occupancy)
propDiag <- round(prop.table(cntDiag) * 100 , digits = 1)
cntDiag
result: 
0    1 
6414 1729 

## Modeling
text and code here

## Evaluation and Deployment
text and code here

reviewer adds suggestions for improving the model
